services:

  backend:
      build: .
      restart: always
      ports:
      - "8000:8000"
      depends_on:
        - db
      env_file:
        - .env

  db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - .env


volumes:
  postgres_data: